name = "Don"
type = "javascript"

# Build configuration (if applicable)
[build]
command = "pnpm build"
cwd = "."

# Cache-Control headers for caching assets for 30 days
[[headers]]
for = "*"
Cache-Control = "public, max-age=2592000"
ETag = "W/etag"
